# Generated by Django 4.0.3 on 2022-04-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='criado',
            field=models.DateField(auto_now_add=True, verbose_name='Data de criação'),
        ),
    ]
